version: "1.0"
projects:
  - name: "staffing-web-main"
    ide: QDJS
    projectPath: "."
    qodanaYamlPath: "qodana.yaml"

profiles:
  - name: default
    inspections:
      - group: ALL
        enabled: true